name: gsmp
version: '0.1'
main: com.redwoodsteve.gsmp.Gsmp
api-version: '1.21'
authors: [redwoodsteve]
description: goober smp plugin
website: mcs.redwoodsteve.com

commands:
  space:
    description: sends you to outer space!
    usage: /<command>